uint8 DIR_LEFT=0
uint8 DIR_RIGHT=1
uint8 DIR_NEUTRAL=2
uint8 grip_direction            # grip left, right or return to the neutral position
---
float32 relative_grip_change    # change in grip relative to the previous position, unitless quantity
---
float32 relative_grip_change    # change in grip relative to the previous position, unitless quantity